In [1]:
import footprint_attributes
import geopandas as gpd

In [2]:
help(footprint_attributes.calc_forces)

Help on function calc_forces:

calc_forces(geoms: geopandas.geodataframe.GeoDataFrame, buffer: float = 0, height_column: str = None) -> geopandas.geodataframe.GeoDataFrame
    Calculates force-based metrics for building footprints based on their geometry and proximity.

    Parameters:
        geoms (gpd.GeoDataFrame): A GeoDataFrame containing building footprints as polygon geometries.
        buffer (float): Buffer distance in meters to determine if two buildings are considered touching.
        height_column (str, optional): Column name in `geoms` specifying the building height in meters.
                                       If `None`, all buildings are assumed to have a uniform height of 1.

    Returns:
        gpd.GeoDataFrame: The input GeoDataFrame with the following new columns:
            - "momentum": Momentum of the resultant force with respect to the footprint centroid.
              Formula: sum(distance * |force_i|)
            - "force": Magnitude of the resultant force acting on the footprint.
              Formula: |sum(force_i)|
            - "confinement_ratio": Proportion of total forces that are confined (counterbalanced by opposing forces).
              Formula: (sum(|force_i|) - |sum(force_i)|) / |sum(force_i)|
            - "angle": Normalized sum of the angles between individual forces and the resultant force.
              Formula: sum(|force_i| * angle(force_i, sum(force_j))) / |sum(force_i)|

    Notes:
        - This method assumes that forces are calculated based on proximity and building height.
        - The buffer determines which buildings are close enough to interact.

In [3]:
region = 'costa_rica'
base_path = 'C:\Topo\ProyectoExpoSismica\ProyectoPiloto\CostaRica'
footprints_path = base_path + f"\huella\huella_{region}.shp"

In [4]:
footprints_gdf = gpd.read_file(footprints_path)
footprints_gdf = footprints_gdf.explode()
#footprints_gdf = footprints_gdf.loc[footprints_gdf['gid'].isin([1817,1811]),:]
footprints_gdf

        gid                                           geometry
0    1218.0  POLYGON ((488600.239 1097577.417, 488591.045 1...
1    1219.0  POLYGON ((488562.593 1097585.096, 488567.403 1...
2    1220.0  POLYGON ((488601.331 1097581.438, 488599.351 1...
3    1221.0  POLYGON ((488517.642 1097593.605, 488517.592 1...
4    1222.0  POLYGON ((488492.697 1097591.081, 488492.546 1...
..      ...                                                ...
943  1273.0  POLYGON ((488958.217 1097631.443, 488961.413 1...
944  1333.0  POLYGON ((489119.978 1097677.125, 489130.663 1...
945  3632.0  POLYGON ((489024.946 1097763.628, 489024.157 1...
946  1505.0  POLYGON ((488924.894 1097824.766, 488928.927 1...
947  1792.0  POLYGON ((489149.749 1097961.201, 489134.034 1...

[944 rows x 2 columns]

In [5]:
footprints_gdf = footprint_attributes.calc_forces(footprints_gdf,height_column=None,buffer=0.2) #20 cm of buffer
footprints_gdf

,gid,geometry,force,confinement_ratio,momentum,angle
0,1218.0,"POLYGON ((488600.239 1097577.417, 488591.045 1...",7.513425,2.119091,6.640663,2.465851e+00
1,1219.0,"POLYGON ((488562.593 1097585.096, 488567.403 1...",8.049236,0.766662,74.113762,1.159873e+00
2,1220.0,"POLYGON ((488601.331 1097581.438, 488599.351 1...",2.622882,7.681600,0.023393,2.060583e-01
3,1221.0,"POLYGON ((488517.642 1097593.605, 488517.592 1...",0.215113,179.790671,2.818897,2.266605e+00
4,1222.0,"POLYGON ((488492.697 1097591.081, 488492.546 1...",2.944814,0.000000,5.556207,0.000000e+00
...,...,...,...,...,...,...
943,1273.0,"POLYGON ((488958.217 1097631.443, 488961.413 1...",18.393086,0.000000,1.608364,0.000000e+00
944,1333.0,"POLYGON ((489119.978 1097677.125, 489130.663 1...",9.216480,0.000000,5.033352,4.214685e-08
945,3632.0,"POLYGON ((489024.946 1097763.628, 489024.157 1...",8.150671,1.111545,16.661893,1.587350e+00
946,1505.0,"POLYGON ((488924.894 1097824.766, 488928.927 1...",5.649423,1.679563,8.155409,1.745959e+00
947,1792.0,"POLYGON ((489149.749 1097961.201, 489134.034 1...",14.410721,0.497552,88.492397,1.790336e-02

In [6]:
footprints_gdf = footprint_attributes.relative_position(footprints_gdf,min_momentum=0.1389,min_confinement=1,min_angle=0.78,min_force=0.1666)
footprints_gdf

,gid,geometry,force,confinement_ratio,momentum,angle,normalized_force,normalized_momentum,relative_position
0,1218.0,"POLYGON ((488600.239 1097577.417, 488591.045 1...",7.513425,2.119091,6.640663,2.465851e+00,0.697807,0.616749,torque
1,1219.0,"POLYGON ((488562.593 1097585.096, 488567.403 1...",8.049236,0.766662,74.113762,1.159873e+00,0.641808,5.909483,torque
2,1220.0,"POLYGON ((488601.331 1097581.438, 488599.351 1...",2.622882,7.681600,0.023393,2.060583e-01,0.341574,0.003046,confined
3,1221.0,"POLYGON ((488517.642 1097593.605, 488517.592 1...",0.215113,179.790671,2.818897,2.266605e+00,0.020213,0.264877,torque
4,1222.0,"POLYGON ((488492.697 1097591.081, 488492.546 1...",2.944814,0.000000,5.556207,0.000000e+00,0.287717,0.542858,partial
...,...,...,...,...,...,...,...,...,...
943,1273.0,"POLYGON ((488958.217 1097631.443, 488961.413 1...",18.393086,0.000000,1.608364,0.000000e+00,1.113140,0.097337,partial
944,1333.0,"POLYGON ((489119.978 1097677.125, 489130.663 1...",9.216480,0.000000,5.033352,4.214685e-08,0.791168,0.432077,partial
945,3632.0,"POLYGON ((489024.946 1097763.628, 489024.157 1...",8.150671,1.111545,16.661893,1.587350e+00,0.977905,1.999068,torque
946,1505.0,"POLYGON ((488924.894 1097824.766, 488928.927 1...",5.649423,1.679563,8.155409,1.745959e+00,0.769893,1.111404,torque
947,1792.0,"POLYGON ((489149.749 1097961.201, 489134.034 1...",14.410721,0.497552,88.492397,1.790336e-02,0.443433,2.723006,partial

In [7]:
footprints_gdf = footprint_attributes.calc_shape_irregularity(footprints_gdf)
footprints_gdf

,gid,geometry,force,confinement_ratio,momentum,angle,normalized_force,normalized_momentum,relative_position,shape_irregularity
0,1218.0,"POLYGON ((488600.239 1097577.417, 488591.045 1...",7.513425,2.119091,6.640663,2.465851e+00,0.697807,0.616749,torque,0.000000
1,1219.0,"POLYGON ((488562.593 1097585.096, 488567.403 1...",8.049236,0.766662,74.113762,1.159873e+00,0.641808,5.909483,torque,0.000148
2,1220.0,"POLYGON ((488601.331 1097581.438, 488599.351 1...",2.622882,7.681600,0.023393,2.060583e-01,0.341574,0.003046,confined,0.000000
3,1221.0,"POLYGON ((488517.642 1097593.605, 488517.592 1...",0.215113,179.790671,2.818897,2.266605e+00,0.020213,0.264877,torque,0.004862
4,1222.0,"POLYGON ((488492.697 1097591.081, 488492.546 1...",2.944814,0.000000,5.556207,0.000000e+00,0.287717,0.542858,partial,0.463150
...,...,...,...,...,...,...,...,...,...,...
943,1273.0,"POLYGON ((488958.217 1097631.443, 488961.413 1...",18.393086,0.000000,1.608364,0.000000e+00,1.113140,0.097337,partial,0.721346
944,1333.0,"POLYGON ((489119.978 1097677.125, 489130.663 1...",9.216480,0.000000,5.033352,4.214685e-08,0.791168,0.432077,partial,0.000000
945,3632.0,"POLYGON ((489024.946 1097763.628, 489024.157 1...",8.150671,1.111545,16.661893,1.587350e+00,0.977905,1.999068,torque,0.338223
946,1505.0,"POLYGON ((488924.894 1097824.766, 488928.927 1...",5.649423,1.679563,8.155409,1.745959e+00,0.769893,1.111404,torque,0.296966
947,1792.0,"POLYGON ((489149.749 1097961.201, 489134.034 1...",14.410721,0.497552,88.492397,1.790336e-02,0.443433,2.723006,partial,3.525004

In [8]:
footprints_gdf = footprint_attributes.calc_polsby_popper(footprints_gdf)
footprints_gdf['shape_irregularity_pp'] = 1-((1-footprints_gdf['shape_irregularity']) * (footprints_gdf['polsby_popper_hull']))
footprints_gdf

,gid,geometry,force,confinement_ratio,momentum,angle,normalized_force,normalized_momentum,relative_position,shape_irregularity,polsby_popper,polsby_popper_hull,shape_irregularity_pp
0,1218.0,"POLYGON ((488600.239 1097577.417, 488591.045 1...",7.513425,2.119091,6.640663,2.465851e+00,0.697807,0.616749,torque,0.000000,0.731584,0.731584,0.268416
1,1219.0,"POLYGON ((488562.593 1097585.096, 488567.403 1...",8.049236,0.766662,74.113762,1.159873e+00,0.641808,5.909483,torque,0.000148,0.570544,0.570725,0.429359
2,1220.0,"POLYGON ((488601.331 1097581.438, 488599.351 1...",2.622882,7.681600,0.023393,2.060583e-01,0.341574,0.003046,confined,0.000000,0.615186,0.615259,0.384741
3,1221.0,"POLYGON ((488517.642 1097593.605, 488517.592 1...",0.215113,179.790671,2.818897,2.266605e+00,0.020213,0.264877,torque,0.004862,0.556486,0.557763,0.444949
4,1222.0,"POLYGON ((488492.697 1097591.081, 488492.546 1...",2.944814,0.000000,5.556207,0.000000e+00,0.287717,0.542858,partial,0.463150,0.554642,0.724261,0.611181
...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,1273.0,"POLYGON ((488958.217 1097631.443, 488961.413 1...",18.393086,0.000000,1.608364,0.000000e+00,1.113140,0.097337,partial,0.721346,0.562271,0.867865,0.758166
944,1333.0,"POLYGON ((489119.978 1097677.125, 489130.663 1...",9.216480,0.000000,5.033352,4.214685e-08,0.791168,0.432077,partial,0.000000,0.780750,0.780750,0.219250
945,3632.0,"POLYGON ((489024.946 1097763.628, 489024.157 1...",8.150671,1.111545,16.661893,1.587350e+00,0.977905,1.999068,torque,0.338223,0.563278,0.772658,0.488673
946,1505.0,"POLYGON ((488924.894 1097824.766, 488928.927 1...",5.649423,1.679563,8.155409,1.745959e+00,0.769893,1.111404,torque,0.296966,0.642602,0.821938,0.422150
947,1792.0,"POLYGON ((489149.749 1097961.201, 489134.034 1...",14.410721,0.497552,88.492397,1.790336e-02,0.443433,2.723006,partial,3.525004,0.353334,0.704585,2.779080

In [9]:
# Plot a map (needs pip install folium matplotlib mapclassify)
footprints_gdf.explore(
    column='normalized_momentum',       # Column to base the color on
    cmap='YlOrRd',        # Color map (Yellow to Red)
    legend=True ,           # Add a legend
    vmin = 0,
    vmax = 1               # Set max and min values
)